Cluster Report : Collect all available log files of a pod (cko-mvp-1)
noironetworks/acc-provision pull request #1003
Opened 2023-08-02 15:36 UTC by pkharat

2023-08-02 16:03 UTC, akhilamohanan requested changes

2023-08-02 16:03 UTC, akhilamohanan commented on provision/testdata/flavor_calico-3.23.2.apic.txt
@pkharat , pls revert changes in this file

2023-08-02 16:03 UTC, akhilamohanan commented on provision/testdata/flavor_calico-3.23.2_tar/custom_resources_aci_calico.yaml
@pkharat , pls revert changes in this file

2023-08-03 05:13 UTC, pkharat commented on provision/testdata/flavor_calico-3.23.2.apic.txt
Reverted it. 
Actual issue is, we do not have test test_flavor_calico_3_23_2 in cko-mvp-1 (but these stale files exists) but it's present in cko-mvp-1 fix-testdata.sh script. We should raise an issue to remove the stale files and remove the test from fix-testdata.sh script

2023-08-03 05:21 UTC, akhilamohanan approved these changes

2023-08-03 05:22 UTC, merged