WIP: Supporting automatic chaining insertion while NAD creation
noironetworks/acc-provision pull request #1057
Opened 2023-11-24 05:48 UTC by YogeshRajmane

2023-12-05 19:43 UTC, shastrinator commented on provision/acc_provision/templates/aci-containers.yaml
> +  annotations:
This should move to the definition of webhook service.

2023-12-05 19:43 UTC, shastrinator commented on provision/acc_provision/templates/aci-containers.yaml
> +  namespace: aci-containers-system
Need serving cert annotation here.

2023-12-06 09:16 UTC, YogeshRajmane commented on provision/acc_provision/templates/aci-containers.yaml
> +  namespace: aci-containers-system
Resolved

2024-01-16 07:50 UTC, shastrinator requested changes

2024-01-16 21:27 UTC, shastrinator approved these changes

2024-01-16 21:27 UTC, merged