Remove install_istio flag
noironetworks/acc-provision pull request #1095
Opened 2024-02-26 15:04 UTC by smshareef

Commented out code for disabling the install_istio flag. Functionality is disabled to remove dependency from istio.io/istio package. Vulnerabilties were detected by quay.io security scan of aci-containers-controller and aci-containers-operator images for istio.io/istio package

2024-02-26 16:29 UTC, akhilamohanan commented on provision/acc_provision/acc_provision.py
> +              " file. Error: %s" % (file_path, ex))
is this change required?

2024-02-26 18:00 UTC, snaiksat commented
Thanks @smshareef . The commit message is a bit misleading. The install_istio config is already disabled by default. What we are taking away is the ability to enable it.

Disabling the configuration to enable install_istio to remove dependency from istio.io/istio package since this feature will not be supported going forward. For the past few cycles we have moved towards supporting Red Hat Service Mesh operator.

2024-02-27 06:02 UTC, snaiksat requested changes

2024-02-27 06:02 UTC, snaiksat commented on provision/acc_provision/templates/provision-config.yaml
>    # install_profile: "default"   # override if needed, default is "demo"
this whole section needs to be removed

2024-02-27 07:30 UTC, smshareef commented on provision/acc_provision/templates/provision-config.yaml
>    # install_profile: "default"   # override if needed, default is "demo"
Done, thanks for the review @snaiksat.

2024-02-27 07:57 UTC, akhilamohanan approved these changes

2024-02-27 13:06 UTC, merged