Added flavors for OCP-4.17 Baremetal, ESX and Openstack
noironetworks/acc-provision pull request #1228
Opened 2024-12-06 07:38 UTC by burhan20

2024-12-06 09:31 UTC, burhan20 commented
> Thanks @burhan20 , please hide 4.14 flavors and also make the corresponding changes on the aci-containers side.

Sure, Sumit

2024-12-06 21:10 UTC, snaiksat requested changes

2024-12-06 21:10 UTC, snaiksat commented on provision/testdata/list_flavors.stdout.txt
>  INFO: openshift-4.11-baremetal:	Red Hat OpenShift Container Platform 4.11 on Baremetal
only 4.17, 4.16, 4.15 should be visible

2024-12-06 21:10 UTC, snaiksat commented on provision/testdata/list_flavors.stdout.txt
>  INFO: openshift-4.11-openstack:	Red Hat OpenShift Container Platform 4.11 on OpenStack
only 4.17, 4.16, 4.15 should be visible

2024-12-06 21:10 UTC, snaiksat commented on provision/testdata/list_flavors.stdout.txt
>  INFO: openshift-4.14-agent-based-esx:	Red Hat OpenShift Container Platform 4.14 on ESX Agent-based Assisted Installation [Experimental]
only 4.16, 4.15 should be visible

2024-12-06 21:10 UTC, snaiksat commented on provision/testdata/list_flavors.stdout.txt
>  INFO: openshift-4.16-agent-based-esx:	Red Hat OpenShift Container Platform 4.16 on ESX Agent-based Assisted Installation [Experimental]
shouldn't we be adding openshift-4.17-agent-based-esx flavor as well?

2024-12-10 01:11 UTC, abhis2112 approved these changes

2024-12-10 03:09 UTC, snaiksat approved these changes

2024-12-10 03:09 UTC, merged