Support for k8s-1.19
noironetworks/acc-provision pull request #416
Opened 2020-11-20 06:59 UTC by PariyaAshok

@snaiksat @apoorva11029 please review the changes.

2020-11-23 05:56 UTC, apoorva11029 approved these changes

2020-12-01 01:33 UTC, snaiksat requested changes

2020-12-01 01:33 UTC, snaiksat commented on provision/acc_provision/versions.yaml
>      cnideploy_version: 5.2.1.0.0ef4718
The following should not be changed. Is there a reason you are changing them??

2020-12-01 03:59 UTC, PariyaAshok commented
Closing this pr, Raised new [pr](https://github.com/noironetworks/acc-provision/pull/417)

2020-12-01 03:59 UTC, closed without merging