Add erspan crd
noironetworks/acc-provision pull request #422
Opened 2020-12-01 21:10 UTC by tanyatukade

2020-12-02 22:54 UTC, jayaramsatya reviewed
LGTM

2020-12-03 04:41 UTC, tomflynn requested changes

2020-12-03 04:41 UTC, tomflynn commented on provision/acc_provision/templates/aci-containers.yaml
> +  version: v1
Can we mark this as alpha like netflow? v1alpha

2020-12-03 16:35 UTC, tanyatukade commented
Will address the comments and open a new PR

2020-12-03 16:35 UTC, closed without merging