Update apic_provision.py to work with python 3.10
noironetworks/acc-provision pull request #622
Opened 2022-05-12 14:11 UTC by mpsOxygen

This solves Issue #614. Thanks @vlella

2022-05-12 15:29 UTC, vlella requested changes
at line 30 after # there should be a space as travis is failing. (Just checked the job log for the respective PR travis build)

2022-05-12 15:35 UTC, vlella commented on provision/acc_provision/apic_provision.py
> +#Try importing Mapping for python 3.10, if it fails default to the older version
at line 30 after # there should be a space as travis is failing. (Just checked the job log for the respective PR travis build)

2022-05-18 13:03 UTC, vlella commented
@mpsOxygen thanks for adding the change!

@snaiksat LGTM

2022-05-18 13:11 UTC, vlella approved these changes

2022-05-19 05:36 UTC, snaiksat approved these changes

2022-05-19 05:36 UTC, merged