ACI-CNI Pods - Provide granular priorityclass options
noironetworks/acc-provision pull request #953
Opened 2023-06-12 13:50 UTC by pkharat

2023-06-12 14:38 UTC, pkharat commented on provision/testdata/with_overrides.kube.yaml
> +      priorityClassName: aci-containers-host
The generated yaml for with_overrides test is not correct, it is setting both the priority class names. The flavor used in this test is kubernetes-1.25. Checking how to fix this.

2023-06-14 01:53 UTC, snaiksat commented
> How would this flow work ? When user want to use these priority classes, user has to set the flag as "use_acicni_priority_class: False" in flavors.yaml 

No, the user never touches flavors.yaml (that file is part of the source code). The suggested logic in our template should take care of overriding that setting, no?

  {% if not config.kube_config.no_priority_class %}
  priorityClassName: system-node-critical
  {% endif %}
  {% if config.kube_config.use_acicni_priority_class %}
  priorityClassName: acicni-priority
  {% if config.kube_config.use_aci_containers_controller_priority_class %}
  priorityClassName: acicni-containers-controller
  {% endif %}

2023-06-14 02:01 UTC, snaiksat requested changes

2023-06-14 02:01 UTC, snaiksat commented on provision/acc_provision/templates/aci-containers.yaml
> +{% endif %}
Can we just do this processing once in the config build stage, set the api version string as a config, and use it here?

2023-06-14 05:52 UTC, pkharat commented
> > How would this flow work ? When user want to use these priority classes, user has to set the flag as "use_acicni_priority_class: False" in flavors.yaml
> 
> No, the user never touches flavors.yaml (that file is part of the source code). The suggested logic in our template should take care of overriding that setting, no?
> 
> ```
> {% if not config.kube_config.no_priority_class %}
> priorityClassName: system-node-critical
> {% endif %}
> {% if config.kube_config.use_acicni_priority_class %}
> priorityClassName: acicni-priority
> {% if config.kube_config.use_aci_containers_controller_priority_class %}
> priorityClassName: acicni-containers-controller
> {% endif %} 
> ```

Overriding is not happening. As I pointed out, always 2 priority class fields are set.
In case of openshift this one (bec flavour.yaml sets "use_acicni_priority_class: True" and "no_priority_class: True")
```
      priorityClassName: acicni-priority
      priorityClassName: aci-containers-host
```

and in case of k8s (1.25) (it has "use_acicni_priority_class: False" and "no_priority_class: False")
```
      priorityClassName: system-cluster-critical
      priorityClassName: aci-containers-host
```

It's because of the if conditions in the containers.yaml. Either one of it is executed for openshift/k8s
```
{% if not config.kube_config.no_priority_class %}
priorityClassName: system-node-critical
{% endif %}
{% if config.kube_config.use_acicni_priority_class %}
priorityClassName: acicni-priority
{% endif %}
```  
And after this the priority class if condition is also executed ending up setting 2 priority class field names.

On further debugging, observed that this issue is seen in kube.yaml only.

Other resource specific yaml in tar folder e.g cluster-network-31-DaemonSet-aci-containers-host.yaml, cluster-network-32-DaemonSet-aci-containers-openvswitch.yaml, cluster-network-33-Deployment-aci-containers-controller.yaml
it has only one priority class field set as expected.

2023-06-14 10:41 UTC, closed without merging

2023-06-14 11:16 UTC, pkharat commented
This branch has conflicts with the master. Did pull master branch changes into this branch and ran fix-testdata.sh, but tests are failing. So(because of time constraints) better closing this PR and creating new branch from master and porting changes to newer branch.

2023-06-14 11:55 UTC, pkharat commented
New PR - https://github.com/noironetworks/acc-provision/pull/961
Addressed all the review comments and changes added to the new PR.